load("//test/test_programs:test_programs.bzl", "test_program")

package(default_visibility = ["//visibility:public"])

test_program(name = "init")

test_program(name = "no_init")

test_program(name = "http_filter_init_fail")

test_program(name = "program_init_fail")

test_program(name = "stream_init")

test_program(name = "get_headers")

test_program(name = "get_body")

test_program(name = "set_headers")

test_program(name = "manipulate_body")

test_program(name = "do_not_close")

test_program(name = "integration_test_headers")

test_program(name = "integration_test_bodies")
