FROM gcr.io/envoy-ci/envoy-build:f94a38f62220a2b017878b790b6ea98a0f6c5f9c@sha256:7adc40c09508f957624c4d2e0f5aeecb73a59207ee6ded53b107eac828c091b2

ARG GIT_SHA_ARG
ARG BAZEL_BUILD_OPTIONS_ARG=""

ARG USERNAME=envoyxbuild
ARG USER_UID=501
ARG USER_GID=$USER_UID
ENV BUILD_DIR=/build

RUN groupadd --gid $USER_GID $USERNAME \
    && useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME -G pcap -d $BUILD_DIR \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

# Install gcc needed for Rust builds (bindgen).
RUN apt-get -y update \
    && apt-get -y install --no-install-recommends gcc g++ \
    && apt-get clean

USER $USERNAME
ENV HOME=$BUILD_DIR

RUN git clone https://github.com/mathetake/envoy-dynamic-modules.git $BUILD_DIR/envoyx

WORKDIR $BUILD_DIR/envoyx
RUN .devcontainer/setup.sh || true
RUN echo "Checking out ${GIT_SHA_ARG}" && git checkout --detach ${GIT_SHA_ARG} && git checkout --detach ${GIT_SHA_ARG}

# To have each layer smaller, we split the bazel build commands.
RUN bazel build $BAZEL_BUILD_OPTIONS_ARG //source/...
RUN bazel test  $BAZEL_BUILD_OPTIONS_ARG //test/...
RUN bazel test  $BAZEL_BUILD_OPTIONS_ARG //sdks/...
RUN bazel build  $BAZEL_BUILD_OPTIONS_ARG //...
RUN bazel test  $BAZEL_BUILD_OPTIONS_ARG //...
