load(
    "@envoy//bazel:envoy_build_system.bzl",
    "envoy_cc_library",
)

envoy_cc_library(
    name = "abi_lib",
    hdrs = ["abi.h"],
    repository = "@envoy",
    visibility = ["//visibility:public"],
)
